######################################################
## Dockerfile para la base de datos cocroach        ##
## Basado en Ubuntu 16.04              		    ##
######################################################

# Imagen Ubuntu oficial versión cockroachdb/cockroach
FROM cockroachdb/cockroach:beta-20161201

MAINTAINER jtierno jtierno

COPY ./ /home

CMD ["bash"]
EXPOSE 8080
EXPOSE 26257

