create table authority (id  bigserial not null, name varchar(50) not null, primary key (id));
create table career (code varchar(255) not null, name varchar(255), primary key (code));
create table career_subject (career_code varchar(255) not null, subject_code varchar(255) not null);
create table class (id int8 not null, day varchar(255), ending_time varchar(255), place varchar(255), starting_time varchar(255), type varchar(255), course_code varchar(255), primary key (id));
create table course (code varchar(255) not null, professors varchar(255), vacancies int8, subject_code varchar(255), primary key (code));
create table registration (course_code varchar(255) not null, user_id int8 not null, registration_date timestamp, primary key (course_code, user_id));
create table security_user (id  bigserial not null, enabled boolean not null, firstname varchar(50) not null, lastpasswordresetdate timestamp not null, lastname varchar(50) not null, password varchar(100) not null, username varchar(50) not null, primary key (id));
create table subject (code varchar(255) not null, name varchar(255), primary key (code));
create table system_user (id  bigserial not null, first_name varchar(255), last_name varchar(255), user_name varchar(255), career_code varchar(255), primary key (id));
create table system_user_registrations (user_id int8 not null, registrations_course_code varchar(255) not null, registrations_user_id int8 not null, primary key (user_id, registrations_course_code, registrations_user_id));
create table user_authority (user_id int8 not null, authority_id int8 not null);
create index idx_career_subject_sub on career_subject (subject_code);
create index idx_career_subject_car on career_subject (career_code);
create index idx_class_course on class (course_code);
create index idx_course_subject on course (subject_code);
create index idx_reg_id on registration (user_id);
alter table security_user add constraint UK_o716pk0dv59lgrnslah3ngqtd unique (username);
create index idx_user_career_code on system_user (career_code);
alter table system_user add constraint UK_204b9ercidw1baj3s3m9lnr33 unique (user_name);
alter table system_user_registrations add constraint UK_7x83t12d88jn4qo65gvfe5g5n unique (registrations_course_code, registrations_user_id);
create index idx_user_auth_auth on user_authority (authority_id);
create index idx_user_auth_user on user_authority (user_id);
alter table career_subject add constraint FKogkm198bma332j4rho63xb0i7 foreign key (subject_code) references subject;
alter table career_subject add constraint FKas3hym4o4ujtb19byih209h0q foreign key (career_code) references career;
alter table class add constraint FKk95dslf17skblki3ehey3u74a foreign key (course_code) references course;
alter table course add constraint FKf9mvo7mmq877hmye26t1blwb4 foreign key (subject_code) references subject;
alter table registration add constraint FKrrgmnpvde52mihr7wu8assacn foreign key (course_code) references course;
alter table registration add constraint FKq8kkl0alj5j61h758hbinvigl foreign key (user_id) references system_user;
alter table system_user add constraint FKg3hpbv5yv9frb5h6lvcbmo14y foreign key (career_code) references career;
alter table system_user_registrations add constraint FKb1uhg7jmmbite8h1mgcbwfkis foreign key (registrations_course_code, registrations_user_id) references registration;
alter table system_user_registrations add constraint FK3babmgoyrsb15dachw4umcmli foreign key (user_id) references system_user;
alter table user_authority add constraint FKgvxjs381k6f48d5d2yi11uh89 foreign key (authority_id) references authority;
alter table user_authority add constraint FK30jkrhtnjru2qefbgterddjk3 foreign key (user_id) references security_user;